language: generic

os:
  - linux
  - osx

env:
  matrix:
    - PYTHON='2.7'
    - PYTHON='3.5'
    - PYTHON='3.6'
    - PYTHON='3.7'
  matrix:
    - PACKAGE='pip'
    - PACKAGE='conda'

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export OS="Linux"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export OS="MacOSX"; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create --yes --name test-env python=$PYTHON
  - source activate test-env

install:
  - |
    if [ "$PACKAGE" == "pip" ]; then 
      pip install choicemodels pytest
      pip list
    fi
  - |
    if [ "$PACKAGE" == "conda" ]; then 
      conda install choicemodels pytest --channel conda-forge
      conda list
    fi

script:
  - pytest tests/*.py
