language: generic

os:
  - linux
  - osx

env:
  matrix:
    - PYTHON='2.7'
    - PYTHON='3.5'
    - PYTHON='3.6'
    - PYTHON='3.7'

#python:
#  - "2.7"
#  - "3.5"
#  - "3.6"

#matrix:
#  include:
#    - python: "3.7"  # temp solution until travis supports python 3.7 more cleanly
#      dist: xenial
#      sudo: true

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; 
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; 
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create --name test-env python=$PYTHON
  - source activate test-env

install:
  - pip install choicemodels pytest
  - pip list

script:
  - pytest tests/*.py
